export default {
  prova01: {
    es01: { answer01: "c" },
    es02: {
      answer01: "true",
      answer02: "false",
      answer03: "true",
      answer04: "false",
      answer05: "false",
      answer06: "true",
      answer07: "true",
      answer08: "false",
      answer09: "false",
      answer10: "false",
      answer11: "true",
      answer12: "true",
    },
    es03: {
      answer01: "ero",
      answer02: "andavo",
      answer03: "siamo andati",
      answer04: "era",
      answer05: "aveva",
      answer06: "aveva",
      answer07: "si è arrabbiato",
      answer08: "correva",
      answer09: "è caduta",
      answer10: "ha preso",
      answer11: "ha dovuto",
      answer12: "avevo",
      answer13: "ho ricevuto",
      answer14: "ero",
      answer15: "volevo",
      answer16: "conoscevo",
      answer17: "avevate",
      answer18: "vi siete sposati",
      answer19: "ho studiato",
      answer20: "ho iniziato",
    },
    es04: {
      answer01: "era",
      answer02: "sono arrivati",
      answer03: "erano",
      answer04: "esistevano",
      answer05: "usavano",
      answer06: "scrivevano",
      answer07: "telefonavano",
      answer08: "potevi",
      answer09: "ho aspettato",
    },
    es05: {
      answer01: "a",
      answer02: "c",
      answer03: "b",
      answer04: "a",
      answer05: "c",
      answer06: "b",
      answer07: "b",
      answer08: "a",
      answer09: "a",
      answer10: "c",
    },
    es06: {
      answer01: "la",
      answer02: "gli",
      answer03: "mi",
      answer04: "ci",
      answer05: "ne",
    },
    es07: {
      answer01: "c",
      answer02: "c",
      answer03: "b",
      answer04: "c",
      answer05: "a",
      answer06: "c",
      answer07: "a",
      answer08: "b",
    },
    es08: {
      answer01: "false",
      answer02: "true",
      answer03: "false",
      answer04: "true",
      answer05: "false",
      answer06: "true",
      answer07: "false",
      answer08: "true",
      answer09: "false",
      answer10: "true",
    },
    es09: {
      answer01: "true",
      answer02: "false",
      answer03: "true",
      answer04: "false",
      answer05: "true",
      answer06: "false",
      answer07: "true",
      answer08: "true",
    },
  },
  prova02: {
    es01: { answer01: "b" },
    es02: {
      answer01: "false",
      answer02: "false",
      answer03: "true",
      answer04: "true",
      answer05: "false",
      answer06: "false",
      answer07: "true",
      answer08: "true",
      answer09: "false",
      answer10: "true",
      answer11: "false",
      answer12: "true",
    },
    es03: {
      answer01: "la",
      answer02: "le",
      answer03: "ne",
      answer04: "lo",
      answer05: "lo",
      answer06: "li",
    },
    es04: {
      answer01: "le",
      answer02: "gli",
      answer03: "gli",
      answer04: "ti",
      answer05: "mi",
      answer06: "vi",
    },
    es05: {
      answer01: "glieli",
      answer02: "te lo",
      answer03: "glielo",
      answer04: "tele",
      answer05: "gliela",
      answer06: "me lo",
    },
    es06: {
      answer01: "c",
      answer02: "b",
      answer03: "a",
      answer04: "c",
      answer05: "a",
      answer06: "c",
      answer07: "a",
      answer08: "b",
      answer09: "b",
      answer10: "a",
    },
    es07: {
      answer01: "li",
      answer02: "le",
      answer03: "gliel'",
      answer04: "ne",
      answer05: "ci",
      answer06: "vi",
      answer07: "ne",
      answer08: "ci",
      answer09: "glielo",
      answer10: "l'",
    },
    es08: {
      answer01: "c",
      answer02: "b",
      answer03: "a",
      answer04: "b",
      answer05: "a",
      answer06: "c",
      answer07: "b",
      answer08: "b",
    },
    es09: {
      answer01: "true",
      answer02: "false",
      answer03: "false",
      answer04: "false",
      answer05: "true",
      answer06: "true",
      answer07: "true",
      answer08: "false",
      answer09: "false",
      answer10: "true",
    },
    es10: {
      answer01: "false",
      answer02: "true",
      answer03: "true",
      answer04: "false",
      answer05: "true",
      answer06: "false",
      answer07: "true",
      answer08: "true",
    },
  },
  prova03: {
    es01: { answer01: "c" },
    es02: {
      answer01: "true",
      answer02: "true",
      answer03: "false",
      answer04: "true",
      answer05: "false",
      answer06: "false",
      answer07: "false",
      answer08: "true",
      answer09: "false",
      answer10: "false",
      answer11: "true",
      answer12: "true",
    },
    es03: {
      answer01: "marco la prepara",
      answer02: "elena le scrive",
      answer03: "mio figlio ne ha mangiati quattro",
      answer04: "digli che gli saluto",
      answer05: "comprane due chili",
      answer06: "li hai visti?",
      answer07: "voglio regalargli una bambola",
      answer08: "ne prendo ancora una fetta",
      answer09: "mi sono dimenticata di telefonarle",
      answer10: "posso averne ancora un po'?",
      answer11: "le chiedo un'informazione",
    },
    es04: {
      answer01: "mi",
      answer02: "mi",
      answer03: "gli",
      answer04: "lo",
      answer05: "ti",
      answer06: "ci",
      answer07: "vi",
      answer08: "ne",
      answer09: "li",
      answer10: "ti",
      answer11: "me le",
      answer12: "ne",
      answer13: "gliela",
    },
    es05: {
      answer01: "a",
      answer02: "b",
      answer03: "a",
      answer04: "c",
      answer05: "c",
      answer06: "b",
      answer07: "a",
      answer08: "b",
      answer09: "b",
      answer10: "c",
    },
    es06: {
      answer01: "ti",
      answer02: "gli",
      answer03: "glielo",
      answer04: "ne",
      answer05: "ci",
    },
    es07: {
      answer01: "b",
      answer02: "c",
      answer03: "a",
      answer04: "a",
      answer05: "a",
      answer06: "a",
      answer07: "c",
      answer08: "b",
    },
    es08: {
      answer01: "false",
      answer02: "false",
      answer03: "true",
      answer04: "false",
      answer05: "true",
      answer06: "true",
      answer07: "false",
      answer08: "true",
      answer09: "false",
      answer10: "false",
      answer11: "true",
      answer12: "true",
    },
    es09: {
      answer01: "false",
      answer02: "false",
      answer03: "true",
      answer04: "true",
      answer05: "true",
      answer06: "false",
      answer07: "true",
      answer08: "false",
    },
  },
  prova04: {
    es01: { answer01: "a" },
    es02: {
      answer01: "true",
      answer02: "false",
      answer03: "false",
      answer04: "false",
      answer05: "true",
      answer06: "false",
      answer07: "true",
      answer08: "true",
      answer09: "false",
      answer10: "true",
      answer11: "false",
      answer12: "true",
    },
    es03: {
      answer01: "dal dentista",
      answer02: "che paolo si vuole fare prete",
      answer03: "con veronica",
      answer04: "a fare la spesa",
      answer05: "a casa tua",
      answer06: "che ben arriva tra 5 minuti",
    },
    es04: {
      answer01: "ne",
      answer02: "ne",
      answer03: "ci",
      answer04: "ci",
      answer05: "ne",
      answer06: "ci",
      answer07: "ne",
      answer08: "ci",
      answer09: "ne",
      answer10: "ci",
    },
    es05: {
      answer01: "b",
      answer02: "c",
      answer03: "b",
      answer04: "c",
      answer05: "c",
      answer06: "a",
      answer07: "c",
      answer08: "a",
      answer09: "b",
      answer10: "c",
    },
    es06: {
      answer01: "ne",
      answer02: "ci",
      answer03: "l'",
      answer04: "vela",
      answer05: "ci",
    },
    es07: {
      answer01: "c",
      answer02: "b",
      answer03: "b",
      answer04: "c",
      answer05: "a",
      answer06: "b",
      answer07: "a",
      answer08: "b",
    },
    es08: {
      answer01: "false",
      answer02: "false",
      answer03: "true",
      answer04: "false",
      answer05: "true",
      answer06: "false",
      answer07: "false",
      answer08: "true",
      answer09: "false",
      answer10: "true",
      answer11: "true",
      answer12: "true",
    },
    es09: {
      answer01: "false",
      answer02: "true",
      answer03: "false",
      answer04: "false",
      answer05: "true",
      answer06: "true",
      answer07: "false",
      answer08: "true",
    },
  },
  prova05: {
    es03: {
      answer01: "al",
      answer02: "negli",
      answer03: "in",
      answer04: "della",
      answer05: "a",
      answer06: "della",
      answer07: "in",
      answer08: "in",
      answer09: "dal",
      answer10: "tra i",
      answer11: "da",
    },
    es04: {
      answer01: "agli",
      answer02: "sull'",
      answer03: "della",
      answer04: "sulla",
      answer05: "al",
      answer06: "dell'",
      answer07: "sul",
      answer08: "negli",
      answer09: "agli",
      answer10: "all'",
    },
    es05: {
      answer01: "allo",
      answer02: "dall'",
      answer03: "sul",
      answer04: "dal",
      answer05: "dagli",
      answer06: "della",
      answer07: "dalla",
      answer08: "dal",
      answer09: "al",
      answer10: "alle",
      answer11: "dalla",
      answer12: "all'",
    },
    es07: {
      answer01: "le",
      answer02: "ci",
      answer03: "ne",
      answer04: "mi",
      answer05: "glielo",
      answer06: "li",
      answer07: "li",
      answer08: "ne",
      answer09: "glielo",
      answer10: "ci",
    },
  },
  prova06: {
    es07: {
      answer01: "la",
      answer02: "me lo",
      answer03: "ci",
      answer04: "ne",
      answer05: "vi",
    },
  },
};
