export default function getSolutions() {
  return {
    prova01: {
      es01: { answer01: "c" },
      es02: {
        answer01: "true",
        answer02: "false",
        answer03: "true",
        answer04: "false",
        answer05: "false",
        answer06: "true",
        answer07: "true",
        answer08: "false",
        answer09: "false",
        answer10: "false",
        answer11: "true",
        answer12: "true",
      },
      es03: {
        answer01: "ero",
        answer02: "andavo",
        answer03: "siamo andati",
        answer04: "era",
        answer05: "aveva",
        answer06: "aveva",
        answer07: "si è arrabbiato",
        answer08: "correva",
        answer09: "è caduta",
        answer10: "ha preso",
        answer11: "ha dovuto",
        answer12: "avevo",
        answer13: "ho ricevuto",
        answer14: "ero",
        answer15: "volevo",
        answer16: "conoscevo",
        answer17: "avevate",
        answer18: "vi siete sposati",
        answer19: "ho studiato",
        answer20: "ho iniziato",
      },
      es04: {
        answer01: "era",
        answer02: "sono arrivati",
        answer03: "erano",
        answer04: "esistevano",
        answer05: "usavano",
        answer06: "scrivevano",
        answer07: "telefonavano",
        answer08: "potevi",
        answer09: "ho aspettato",
      },
      es05: {
        answer01: "a",
        answer02: "c",
        answer03: "b",
        answer04: "a",
        answer05: "c",
        answer06: "b",
        answer07: "b",
        answer08: "a",
        answer09: "a",
        answer10: "c",
      },
      es06: {
        answer01: "la",
        answer02: "gli",
        answer03: "mi",
        answer04: "ci",
        answer05: "ne",
      },
      es07: {
        answer01: "c",
        answer02: "c",
        answer03: "b",
        answer04: "c",
        answer05: "a",
        answer06: "c",
        answer07: "a",
        answer08: "b",
      },
      es08: {
        answer01: "false",
        answer02: "true",
        answer03: "false",
        answer04: "true",
        answer05: "false",
        answer06: "true",
        answer07: "false",
        answer08: "true",
        answer09: "false",
        answer10: "true",
      },
      es09: {
        answer01: "true",
        answer02: "false",
        answer03: "true",
        answer04: "false",
        answer05: "true",
        answer06: "false",
        answer07: "true",
        answer08: "true",
      },
    },
    prova02: {
      es01: { answer01: "b" },
      es02: {
        answer01: "false",
        answer02: "false",
        answer03: "true",
        answer04: "true",
        answer05: "false",
        answer06: "false",
        answer07: "true",
        answer08: "true",
        answer09: "false",
        answer10: "true",
        answer11: "false",
        answer12: "true",
      },
      es03: ["la", "le", "ne", "lo", "lo", "li"],
      es04: ["le", "gli", "gli", "ti", "mi", "vi"],
      es05: ["glieli", "te lo", "glielo", "tele", "gliela", "me lo"],
      es06: ["c", "b", "a", "c", "a", "c", "a", "b", "b", "a"],
      es07: [
        "li",
        "le",
        "gliel'",
        "ne",
        "ci",
        "vi",
        "ne",
        "ci",
        "glielo",
        "l'",
      ],
      es08: ["c", "b", "a", "b", "a", "c", "b", "b"],
      es09: [
        "true",
        "false",
        "false",
        "false",
        "true",
        "true",
        "true",
        "false",
        "false",
        "true",
      ],
      es10: ["false", "true", "true", "false", "true", "false", "true", "true"],
    },
  };
}
