export default function getSolutions() {
  return {
    prova01: {
      es01: { answer01: "c" },
      es02: {
        answer01: "true",
        answer02: "false",
        answer03: "true",
        answer04: "false",
        answer05: "false",
        answer06: "true",
        answer07: "true",
        answer08: "false",
        answer09: "false",
        answer10: "false",
        answer11: "true",
        answer12: "true",
      },
      es03: [
        ["ero", "andavo", "siamo andati"],
        ["era", "aveva", "aveva", "si è arrabbiato"],
        ["correva", "è caduta", "ha preso", "ha dovuto"],
        ["avevo", "ho ricevuto", "ero", "volevo", "conoscevo"],
        ["avevate", "vi siete sposati"],
        ["ho studiato", "ho iniziato"],
      ].flat(),
      es04: [
        "era",
        "sono arrivati",
        "erano",
        "esistevano",
        "usavano",
        "scrivevano",
        "telefonavano",
        "potevi",
        "ho aspettato",
      ],
      es05: ["a", "c", "b", "a", "c", "b", "b", "a", "a", "c"],
      es06: ["la", "gli", "mi", "ci", "ne"],
      es07: {
        answer01: "c",
        answer02: "c",
        answer03: "b",
        answer04: "c",
        answer05: "a",
        answer06: "c",
        answer07: "a",
        answer08: "b",
      },
      es08: {
        answer01: "false",
        answer02: "true",
        answer03: "false",
        answer04: "true",
        answer05: "false",
        answer06: "true",
        answer07: "false",
        answer08: "true",
        answer09: "false",
        answer10: "true",
      },
      es09: {
        answer01: "true",
        answer02: "false",
        answer03: "true",
        answer04: "false",
        answer05: "true",
        answer06: "false",
        answer07: "true",
        answer08: "true",
      },
    },
    prova02: {
      es01: ["b"],
      es02: [
        "false",
        "false",
        "true",
        "true",
        "false",
        "false",
        "true",
        "true",
        "false",
        "true",
        "false",
        "true",
      ],
      es03: ["la", "le", "ne", "lo", "lo", "li"],
      es04: ["le", "gli", "gli", "ti", "mi", "vi"],
      es05: ["glieli", "te lo", "glielo", "tele", "gliela", "me lo"],
      es06: ["c", "b", "a", "c", "a", "c", "a", "b", "b", "a"],
      es07: [
        "li",
        "le",
        "gliel'",
        "ne",
        "ci",
        "vi",
        "ne",
        "ci",
        "glielo",
        "l'",
      ],
      es08: ["c", "b", "a", "b", "a", "c", "b", "b"],
      es09: [
        "true",
        "false",
        "false",
        "false",
        "true",
        "true",
        "true",
        "false",
        "false",
        "true",
      ],
      es10: ["false", "true", "true", "false", "true", "false", "true", "true"],
    },
  };
}
